### ISSUE TITLE
Phylogenetic tree interaction

### ISSUE THREAD

**Issue by arbreurkes** [ProgrammingLife2016/PL4-2016#68]
Strains should be selectable in the phylogenetic tree.

**Comment by arbreurkes** [comment]
First interaction merged into master at #72

**Comment by arbreurkes** [comment]
@tieswesterborg will partially take over to make sure the graph loading is done correctly.

**Comment by tieswesterborg** [comment]
Im almost done, still needs some bugfixes. Also @dvantetering will help to fix a ZoomBox issue

**Comment by arbreurkes** [comment]
All done.
