### ISSUE TITLE
Bubble cells sometimes change to Rectangle cells when zooming out

### ISSUE THREAD

**Issue by ghost** [ProgrammingLife2016/PL4-2016#77]
Whenever a bubble cell is part of further collapses it will again be drawn as a bubble cell. As soon as a bubble cell is not a part of a further collapse it is drawn as a rectangle cell.

**Comment by NielsW-dev** [comment]
Whenever a bubble cell is part of further collapses it will again be drawn as a bubble cell. As soon as a bubble cell is not a part of a further collapse it is drawn as a rectangle cell.

**Comment by ghost** [comment]
False positive, a bug seemed to be present due to overlapping nodes.
